# Generated by Django 5.2.6 on 2025-10-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_cotizacion_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='valido_hasta',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='valido_hasta',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
    ]
