"""
Django settings for mixnow project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8ojwgprslt$ccy4ek4x^2uih*jlp-*p#pb32#i1jhfffzl(t^!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['cotizaciones-ald3.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'registration',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'app.middleware.security_headers.RemoveServerHeaderMiddleware', 
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'mixnow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mixnow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'       # Español
TIME_ZONE = 'America/Santiago'  # Ajusta a tu zona
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


LOGIN_URL = 'login'   # nombre de la ruta del login
LOGIN_REDIRECT_URL = 'inicio'  # a dónde va después de loguearse
LOGOUT_REDIRECT_URL = 'login'

#LA SESION SE CIERRA AUTOMATICAMENTE 
#AL CERRAR EL NAVEGADOR PARA PROTEGER EL SISTEMA
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#CONFIGURACIONES PARA PROTEGER LAS COOKIES Y QUE NO SE FILTRES , 
# Y ASI EVITAR ROBOS DE INICIO DE SESION O INFO POR MEDIO DE LAS COOKIES (ARCHIVOS FORMATO TXT)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True        # si usas HTTPS en staging/producción
SESSION_COOKIE_SAMESITE = 'Lax'     # o 'Strict' según compatibilidad
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Expiración de sesión
SESSION_COOKIE_AGE = 60*60*24  # 1 día, ajusta según necesidad

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",),
        'script-src': (
            "'self'",
            'https://cdn.jsdelivr.net',
            'https://cdnjs.cloudflare.com'
        ),
        'style-src': (
            "'self'",
            'https://fonts.googleapis.com',
            'https://cdn.jsdelivr.net',      # si usas Bootstrap desde CDN
            'https://cdnjs.cloudflare.com',  # si usas FontAwesome desde CDN
            "'unsafe-inline'",               # necesario si usas inline styles
        ),
        'font-src': (
            "'self'",
            'https://fonts.gstatic.com',
        ),
        'img-src': ("'self'", 'data:'),
    }
}



